### ISSUE TITLE
Texture issues discovered.

### ISSUE THREAD

**Issue by dajix350** [Offroaders123/EM32D-Bedrock#1]
I was testing out this texture pack a few minutes ago. I was using a texture pack test world I found on [MCEPDL](https://mcpedl.com/texture-pack-and-shader-testing-world/). I found that there are no 32x coloured terracotta textures,

Thanks for making a bedrock port of this awesome pack,

**Comment by Offroaders123** [comment]
Thanks for the bug report!

**Comment by Offroaders123** [comment]
Alright, this should now be fixed!
Thanks again for sharing that you found it.
[Commit with the texture additions](https://github.com/Offroaders123/EM32D-Bedrock/commit/6fb56709d560f07fb2ec399ef3d30b9a0915211f)
